services:

  api:
    build: .
    image: transcription-api:latest
    container_name: api

    command: sh -c "alembic upgrade head && uvicorn api.main:app --host 0.0.0.0 --port 8000"

    ports:
      - "8000:8000"

    volumes:
      - ./ml_models:/home/app/ml_models
      - temp:/home/app/temp

    depends_on:
      db:
        condition: service_healthy

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  worker:
    build: .
    image: transcription-api:latest
    container_name: worker

    command: >
      celery
      -A api.core.celery:celery
      worker
      --pool=solo
      --loglevel=info

    volumes:
      - ./ml_models:/home/app/ml_models
      - temp:/home/app/temp

    depends_on:
      - redis

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  redis:
    image: redis:8-alpine
    container_name: redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

  db:
    image: pgvector/pgvector:pg16
    container_name: db

    ports:
      - "127.0.0.1:5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 2s

volumes:
  postgres_data:
  redis_data:
  temp: