"""squashed migration

Revision ID: 164c402e5b84
Revises: 
Create Date: 2026-07-13 15:37:05.696853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '164c402e5b84'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

processing_status = postgresql.ENUM('PENDING', 'PROCESSING', 'SUCCESS', 'FAILURE', name='processing_status', create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    processing_status.create(bind, checkfirst=True)

    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', processing_status, server_default='PENDING', nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=True),
    sa.Column('status', processing_status, server_default='PENDING', nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operators')
    op.drop_table('conversations')
    # ### end Alembic commands ###

    processing_status.drop(bind, checkfirst=True)
