"""add operator-conversations relationship

Revision ID: 4480d5cdf2fe
Revises: 164c402e5b84
Create Date: 2026-07-15 15:27:31.198675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4480d5cdf2fe'
down_revision: Union[str, Sequence[str], None] = '164c402e5b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('operator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'operators', ['operator_id'], ['id'], ondelete='SET NULL')
    op.add_column('operators', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operators', 'is_active')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'operator_id')
    # ### end Alembic commands ###
