"""add external_id for operators

Revision ID: 7c8f8392857c
Revises: c7be4d352ca9
Create Date: 2026-08-16 15:18:05.618176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8f8392857c'
down_revision: Union[str, Sequence[str], None] = 'c7be4d352ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operators', sa.Column('external_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_operators_external_id'), 'operators', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operators_external_id'), table_name='operators')
    op.drop_column('operators', 'external_id')
    # ### end Alembic commands ###
